name: build

on: [push]

jobs:
  linux_clang6:
    name: "Linux Clang6"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ job.container.id }}-ccache-${{ github.sha }}
        restore-keys: ${{ job.container.id }}-ccache-

    - run: .ci/linux/run-container.sh 6
    
  linux_clang8:
    name: "Linux Clang8"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ job.container.id }}-ccache-${{ github.sha }}
        restore-keys: ${{ job.container.id }}-ccache-

    - run: .ci/linux/run-container.sh 8
    - uses: kittaakos/upload-artifact-as-is@v0
      with: 
        path: upload/
    
  android:
    name: "Android"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ job.container.id }}-ccache-${{ github.sha }}
        restore-keys: ${{ job.container.id }}-ccache-

    - run: .ci/android/run-container.sh
    - uses: kittaakos/upload-artifact-as-is@v0
      with: 
        path: upload/
    
  macos:
    name: "macOS"
    runs-on: macOS-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ job.container.id }}-ccache-${{ github.sha }}
        restore-keys: ${{ job.container.id }}-ccache-
          
    - run: .ci/macos/install-dependencies.sh
    - run: .ci/macos/build.sh
    - uses: kittaakos/upload-artifact-as-is@v0
      with: 
        path: upload/
    
# TODO: Add Windows