name: build

on: [push]

jobs:
  linux_clang6:
    name: "Linux Clang6"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Prepare cache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: ${{ runner.os }}-ccache-

    - name: Build
      run: .ci/linux/run-container.sh 6
    
  linux_clang8:
    name: "Linux Clang8"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Prepare cache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: ${{ runner.os }}-ccache-

    - name: Build
      run: .ci/linux/run-container.sh 8

    - name: Upload
      uses: kittaakos/upload-artifact-as-is@v0
      with: 
        path: upload/
    
  android:
    name: "Android"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Prepare cache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: ${{ runner.os }}-ccache-

    - name: Build
      run: .ci/android/run-container.sh

    - name: Upload
      uses: kittaakos/upload-artifact-as-is@v0
      with: 
        path: upload/
    
  macos:
    name: "macOS"
    runs-on: macOS-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Prepare cache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: ${{ runner.os }}-ccache-

    - name: Install
      run: .ci/macos/install-dependencies.sh
    
    - name: Build
      run: .ci/macos/build.sh
    
    - name: Upload
      uses: kittaakos/upload-artifact-as-is@v0
      with: 
        path: upload/
    
# TODO: Add Windows